odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true #false

frequency: 50

odom0: odometry/gps
odom0_config: [true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: false
odom0_differential: true

# odom1: mono_odometer/odometry
# odom1_config: [true,  true,  false,
               # false, false, false,
               # false, false, false,
               # false, false, false,
               # false, false, false]
# odom1_queue_size: 10
# odom1_nodelay: false
# odom1_differential: true

imu0: imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
imu0_queue_size: 10
imu0_nodelay: false
imu0_differential: false
imu0_remove_gravitational_acceleration: true
